#!/bin/bash
./check-commit
if [ $? -eq 2 ]
then
  if ! git diff --quiet
  then
    echo "Push cancelled, changed files present"
    echo "do \"git push\" yourself"
    exit 1
  fi
fi
git push
if [ $? -ne 0 ]
then
    echo
    echo $(tput setab 1)$(tput setaf 7)*** GIT-PUSH Failed ***$(tput sgr0)
    echo
fi

echo
echo $(tput setab 2)$(tput setaf 7)*** GIT-PUSH SUCCESS ***$(tput sgr0)
echo

git push --tags

