#!/bin/bash
./check
if [ $? -eq 1 ] 
then
    echo "Check Failed"
    exit 1
fi
git add .
git commit -v
if [ $? -eq 1 ]
then
    # most likely empty message
    echo "Exiting, commit failed"
    exit 2
fi
